backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "site/img" # Media files will be stored in the repo under images/uploads

collections:

  # Blogs
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "site/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: " " }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Subtitle", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  # Our pages e.g. Home, About
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Wide", name: "wide", widget: "boolean", required: false }
      - { label: "Hide Title", name: "hideTitle", widget: "boolean", required: false }
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - { label: "page", value: "layouts/base.njk" }
          - { label: "blog", value: "layouts/blog.njk" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }


  # Site Settings
  - name: "site"
    label: "Site Settings"
    files:
      - label: "Custom CSS"
        name: "css"
        file: "site/css/custom.css.md"
        fields:
          - { label: "Custom CSS", name: "body", widget: "code", default_language: 'css', output_code_only: true }
      - label: "Site Metadata"
        name: "metadata"
        file: "site/data/metadata.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Footer"
        name: "footer"
        file: "site/footer.html"
        fields:
          - { label: "footer", name: "body", widget: "code", default_language: 'html', output_code_only: true }
      - label: "Head"
        name: "head"
        file: "site/head.html"
        fields:
          - { label: "footer", name: "body", widget: "code", default_language: 'html', output_code_only: true }
